PROGS_SCHED_CHECK_OBJS := sched_check.o
PROGS_SCHED_CHECK_OBJS := $(PROGS_SCHED_CHECK_OBJS:%=$(TDIR)/sched_check/%)
ALL_OBJS += $(PROGS_SCHED_CHECK_OBJS)

$(TDIR)/bin/sched_check : $(TSTART) $(PROGS_SCHED_CHECK_OBJS) $(TLIBC)

