PROGS_BUTTERKNIFE_OBJS:= butterknife.o
PROGS_BUTTERKNIFE_OBJS := $(PROGS_BUTTERKNIFE_OBJS:%=$(TDIR)/butterknife/%)
ALL_OBJS += $(PROGS_BUTTERKNIFE_OBJS)

$(TDIR)/bin/butterknife : $(TSTART) $(PROGS_BUTTERKNIFE_OBJS) $(TLIBC)

